### ISSUE TITLE
RangeError: Invalid array length on ascii-table.js line 95

### ISSUE THREAD

**Issue by m4olivei** [sorensen/ascii-table#9]
Hi,

I'm using phantomas, which uses ascii-table.js.  On certain runs of that tool I was getting this error:

```
usr/local/lib/node_modules/phantomas/node_modules/ascii-table/ascii-table.js:95
  return str + Array(len + 1 - str.length).join(pad)
               ^
RangeError: Invalid array length
    at Function.AsciiTable.alignLeft (/usr/local/lib/node_modules/phantomas/node_modules/ascii-table/ascii-table.js:95:16)
    at Function.AsciiTable.align (/usr/local/lib/node_modules/phantomas/node_modules/ascii-table/ascii-table.js:70:50)
    at AsciiTable._renderTitle (/usr/local/lib/node_modules/phantomas/node_modules/ascii-table/ascii-table.js:552:24)
    at AsciiTable.render.AsciiTable.valueOf.AsciiTable.toString (/usr/local/lib/node_modules/phantomas/node_modules/ascii-table/ascii-table.js:503:20)
    at formatMultipleRunResults (/usr/local/lib/node_modules/phantomas/reporters/plain.js:142:16)
    at Object.render (/usr/local/lib/node_modules/phantomas/reporters/plain.js:152:12)
    at Object.render (/usr/local/lib/node_modules/phantomas/core/reporter.js:64:20)
    at /usr/local/lib/node_modules/phantomas/bin/phantomas.js:191:19
    at /usr/local/lib/node_modules/phantomas/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/phantomas/node_modules/async/lib/async.js:157:25
```

After a little debugging, I found that the problem was that a negative array length was being passed to the Array constructor here:

https://github.com/sorensen/ascii-table/blob/master/ascii-table.js#L90

I solved it by checking to make sure the calculated length is greater than 0:

```js
if ((len + 1 - str.length) > 0) {
  return str + Array(len + 1 - str.length).join(pad)
}
else {
  return str;
}
```

Makes for an uneven table, but at least it doesn't break.  Sorry I didn't make a proper PR.

**Comment by m4olivei** [comment]
:+1:

**Comment by sorensen** [comment]
Thanks for finding the issue!

**Comment by sorensen** [comment]
@m4olivei I've added you to the contributors list if that is ok.

**Comment by m4olivei** [comment]
Absolutely!
